var team_choiceA = 0;
var team_choiceB = 1;
var determinA = team_choiceA * 10;
var determinB = team_choiceB * 10;
var orderA = new Array(10);
var orderB = new Array(10);
var count_out = 0;
var inning = 1;
var half = 0;